import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from "./provider";
import Appbar from "./components/Appbar";
import { ToastContainer } from "react-toastify";
import 'react-toastify/dist/ReactToastify.css';

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="dark">
      <body className={inter.className}>
        <Providers>
          <Appbar/>
        {children}
        <ToastContainer/>
        </Providers>
        </body>
    </html>
  );
}
